name: Terraform Plan

on:
  push:
    branches:
      - "**"

env:
  TF_VERSION: 1.8.0
  TF_WORKING_DIR: terraform
  TF_BACKEND_BUCKET: cong-iac-terraform-state

jobs:
  plan:
    name: Terraform Plan (${{ matrix.environment }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, staging, prod]

    defaults:
      run:
        working-directory: terraform/environments/${{ matrix.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Directory
        run: mkdir -p ${{ env.TF_WORKING_DIR }}

      - name: Write GCP credentials to file safely
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > gcp-key.json

      - name: Export ADC credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init - prefix gke/${{ matrix.environment }}
        run: |
          terraform init \
            -no-color \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="prefix=gke/${{ matrix.environment }}"

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=env.tfvars

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}-${{ github.sha }}
          path: terraform/environments/${{ matrix.environment }}/tfplan-${{ matrix.environment }}-${{ github.sha }}

      - name: Output Commit Info
        run: echo "::notice::Use commit SHA '${GITHUB_SHA}' to run apply"
