name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment shall be destroyed?"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm_destroy:
        description: "Enter 'true' to confirm destroy"
        required: true
        default: "false"

env:
  TF_VERSION: 1.8.0
  TF_BACKEND_BUCKET: cong-iac-terraform-state

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy - ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    if: github.ref == 'refs/heads/main' && github.event.inputs.confirm_destroy == 'true'

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud (via WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: terraform-ci@niclas-test.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init -no-color

      - name: Terraform Destroy
        run: terraform destroy -no-color -auto-approve
