name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment shall be destroyed?"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm_destroy:
        description: "Enter 'true' to confirm destroy"
        required: true
        default: "false"

env:
  TF_VERSION: 1.8.0
  TF_BACKEND_BUCKET: cong-iac-terraform-state

jobs:
  destroy:
    name: Terraform Destroy - ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment != 'dev' && format('{0}', github.event.inputs.environment) || null }}
    if: github.ref == 'refs/heads/main' && github.event.inputs.confirm_destroy == 'true'

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init -no-color \
          -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
          -backend-config="prefix=gke/${{ github.event.inputs.environment }}"

      - name: Terraform Destroy
        run: terraform destroy -no-color -auto-approve
