name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

env:
  TF_VERSION: "1.8.0"
  TF_WORKING_DIR: "./terraform"

jobs:
  apply:
    name: Terraform Apply (on main)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ${{ env.TF_WORKING_DIR }}
      - run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > gcp-key.json
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - run: terraform init
      - run: terraform apply -auto-approve -var="gcp_project=${{ secrets.GOOGLE_PROJECT }}" -var="gcp_region=${{ secrets.GOOGLE_REGION }}"
