name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Welche Umgebung soll deployed werden?"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TF_VERSION: 1.8.0
  TF_WORKING_DIR: terraform
  TF_BACKEND_BUCKET: cong-iac-terraform-state

jobs:
  apply:
    name: Terraform Apply - ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Directory
        run: mkdir -p ${{ env.TF_WORKING_DIR }}

      - name: Write GCP credentials to file safely
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > gcp-key.json

      - name: Export ADC credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init \
            -no-color \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="prefix=gke/${{ github.event.inputs.environment }}"

      - name: Generate tfvars file dynamically
        run: |
          echo "gcp_project=\"${{ secrets.GOOGLE_PROJECT }}\"" > env.tfvars
          echo "gcp_region=\"${{ secrets.GOOGLE_REGION }}\"" >> env.tfvars

          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "gke_cluster_name=\"${{ secrets.DEV_CLUSTER_NAME }}\"" >> env.tfvars
            echo "gke_node_count=${{ secrets.DEV_NODE_COUNT }}" >> env.tfvars
          elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "gke_cluster_name=\"${{ secrets.STAGING_CLUSTER_NAME }}\"" >> env.tfvars
            echo "gke_node_count=${{ secrets.STAGING_NODE_COUNT }}" >> env.tfvars
          else
            echo "gke_cluster_name=\"${{ secrets.PROD_CLUSTER_NAME }}\"" >> env.tfvars
            echo "gke_node_count=${{ secrets.PROD_NODE_COUNT }}" >> env.tfvars
          fi

      - name: Terraform Plan
        run: terraform plan -var-file=env.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -no-color -auto-approve -var-file=env.tfvars
